### ISSUE TITLE
Use small resource class 

### ISSUE THREAD

**Issue by HormyAJP** [ganezasan/auto-cancel-workflow-orb#2]
Suggest updating the executor to use a small resource class. There's no point wasting $ on anything else for this.

```
executors:
  default:
    docker:
      - image: circleci/node:latest
```

Alternatively, maybe make it configurable via a param. Although I'm not sure if that's possible.
